version = 0.1
[default.deploy.parameters]
stack_name = "AdGenie-backend2"
resolve_s3 = true
s3_prefix = "AdGenie-backend2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "InstagramClientIdParameter=\"709167811435160\"",
    "InstagramClientSecretParameter=\"117a3342aab3f9c901403f195f5ea5c0\""
]
